# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d676ed0bc019892202bba077ec35dd14c1e45785f79362f60bec58d98c78fc1678a129de820ceadbb9f3cc8011db2e3751a34feb8f043b0d83db0b3d6e0bc28e

test:
  secret_key_base: 63460069474d6c5bdf679d863de2f00bdaa74a0453654fd91effa86a8edb508493733853faf9df2e0034fc25c990b76a3c22e7122a38c56b7091b641beb9abf5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
